;----------------------------------------------------------------------------
; QRC UI Version: 9.1.2
;----------------------------------------------------------------------------

vuiRcxSetupFormOptions = '(
    ((?vuiRCXFlowTab)
        (vuiOutputFormatSpiceButton      t)
        (rcxSetRsfIncludeReadOnly      nil)
        (subNode      nil)
        (extractMosAp      nil)
        (callProcReadOnly      nil)
        (extractMosDiff      "NONE")
        (p2lvsSetBoolReadOnly      nil)
        (grayBoxReadOnly      nil)
        (substrateProfile      "NONE")
        (vuiOutputFormatSpectreButton      t)
        (vuiOutputFormatExtractedViewButton      t)
        (rcxRsfInclude      "")
        (parasiticResComp      "presistor")
        (ind1PropIdentifier      "ind1")
        (vuiOutputFormatTransistorDspfButton      t)
        (ind2PropIdentifier      "ind2")
        (indPropIdentifierReadOnly      nil)
        (addLvsMosResReadOnly      nil)
        (extractMosDiffReadOnly      nil)
        (vuiOutputFormatTransistorSpefButton      t)
        (ind2PropIdentifierReadOnly      nil)
        (libPrefix      "")
        (substrateExtractReadOnly      nil)
        (parasiticIndCompReadOnly      nil)
        (extractMosApReadOnly      nil)
        (addBulkTerminal      nil)
        (extractMosRes      nil)
        (extractMosResReadOnly      nil)
        (addBulkTerminalReadOnly      nil)
        (parasiticCapComp      "pcapacitor")
        (devPropFile      "")
        (rcxSetRsfInclude      nil)
        (resPropIdentifierReadOnly      nil)
        (rcxRsfIncludeReadOnly      nil)
        (substrateProfileReadOnly      nil)
        (p2lvsSetBool      nil)
        (parasiticCapCompReadOnly      nil)
        (vuiOutputFormatLvsExtractedViewButton      t)
        (mindPropIdentifier      "k")
        (grayBox      nil)
        (vuiOutputFormatSpefButton      t)
        (parasiticMIndComp      "pmind")
        (addLvsMosRes      nil)
        (resPropIdentifier      "r")
        (capPropIdentifier      "c")
        (vuiOutputFormatDspfButton      t)
        (parasiticMIndCompReadOnly      nil)
        (ind1PropIdentifierReadOnly      nil)
        (callProc      "")
        (capPropIdentifierReadOnly      nil)
        (parasiticIndComp      "pinductor")
        (substrateExtract      nil)
        (vuiRCXDefaultOutputFormatType      "Spice")
        (parasiticResCompReadOnly      nil)
        (indPropIdentifier      "l")
        (checkCellView      nil)
        (mindPropIdentifierReadOnly      nil)
    )
    ((?vuiRCXExtractionTab)
        (vuiRCXRLCK      t)
        (vuiRCXEnableRCXFS      t)
        (ladderNetwork      nil)
        (Maxfracturelength      "infinite")
        (vuiRCXSNP      t)
        (splitPinDistance      "5")
        (capExtractMode      "Decoupled")
        (layerSetupCustomBool      nil)
        (resistMeshBool      nil)
        (refNode      "")
        (rcxfsHigh      nil)
        (vuiRCXFSFCAN      nil)
        (vuiRcxFSExtractionCheckLimit      "NONE")
        (vuiRCXCOnly      t)
        (vuiRCXROnly      t)
        (vuiRCXSP      t)
        (parasBlockDevCellsFile      "")
        (vuiRCXEHrcx      t)
        (vuiRCXFCAN      t)
        (outperformConfigFileField      "")
        (splitPins      nil)
        (outperformConfigFileSet      nil)
        (vuiRCXFSSP      nil)
        (vuiRCXFSSN      nil)
        (temperature      "25.0")
        (netNameSpace      "Layout Names")
        (globalFrequency      "0")
        (excludeViaCap      nil)
        (vuiRCXENP      t)
        (fractureLengthUnits      "microns")
        (multFactor      "1.0")
        (vuiRCXRLC      t)
        (vuiRCXFSEN      nil)
        (peecMode      nil)
        (vuiRcxExtractionCheckLimit      "Full Chip All Nets")
        (vuiRCXExtractDefault      "R Only")
        (vuiRCXFCSN      t)
        (contourDirField      "")
        (vuiRCXEN      t)
        (vuiRCXRCOnly      t)
	(layerSetupCustomFile	 "")
	(layerSetupCustom	 "")
	(resistanceMesh	 nil)
    )
    ((?vuiRCXFilteringTab)
        (vuiRCXexcludeFloatLimit      "2000000")
        (vuiRCXmaxViaCountReadOnly      nil)
        (vuiRCXmFactor      "infinite")
        (vuiRCXminCByPerc      "0.1")
        (vuiRCXmaxViaCountBoolReadOnly      nil)
        (vuiRCXArrayViasSpacingReadOnly      nil)
        (vuiRCXmaxViaCount      "1")
        (vuiRCXmaxViaCountBool      nil)
        (vuiRCXexcludeFloatingNets      nil)
        (vuiRCXexcludeSelfCaps      nil)
        (vuiRCXexcludeFloatLimitReadOnly      nil)
        (vuiRCXDanglingR      nil)
        (vuiRCXArrayViasSpacing      "auto")
        (vuiRCXFilterSizeReadOnly      nil)
        (vuiRCXmFactorW      nil)
        (vuiRCXFilterSize      "2.0")
        (vuiRCXexcludeFloatingNetsReadOnly      nil)
        (vuiRCXreduceRC      nil)
        (vuiRCXexcludeSelfCapsReadOnly      nil)
        (vuiRCXmergeParallelR      nil)
        (vuiRCXmFactorWReadOnly      nil)
        (vuiRCXminRReadOnly      nil)
        (vuiRCXreduceRCReadOnly      nil)
        (vuiRCXMaxMergedViaSize      "auto")
        (vuiRCXmergeParallelRReadOnly      nil)
        (vuiRCXminC      "0.01")
        (vuiRCXmFactorReadOnly      nil)
        (vuiRCXminR      "0.001")
        (vuiRCXminCReadOnly      nil)
        (vuiRCXDanglingRReadOnly      nil)
        (vuiRCXMaxMergedViaSizeReadOnly      nil)
    )
    ((?vuiRCXNetlistingTab)
        (vuiRCXCouplingValues      "Double")
        (vuiRCXForceGlobals      nil)
        (outputPostprocessingFile      "")
        (vuiRCXVirtualMetalFillEnable      nil)
        (vuiRCXSubNodeChar      "#")
        (parasiticResTempCoeff      nil)
        (vuiRCXImportGlobals      nil)
        (vuiRCXAddExplicitVias      nil)
        (vuiRCXIgnoreNets      "")
        (vuiRCXInstanceOff      nil)
        (vuiRCXViaEffectOff      nil)
        (vuiRCXXy_D      nil)
        (vuiRCXXy_r      nil)
        (vuiRCXXy_R      nil)
        (vuiRCXIgnoreLayer      "")
        (vuiRCXHierarchyDelimiter      "/")
        (vuiRCXXy_M      nil)
        (vuiRCXResModels      "Do Not Include")
        (vuiRCXXy_c      nil)
        (vuiRCXstampingOff      nil)
        (vuiRCXOutputNetNameSpace      "Schematic")
        (vuiRCXParasiticResWidth      "Off")
        (vuiRCXVirtualMetalFill      "Fine Shape")
        (vuiRCXDeviceFingerDelimiter      "@")
        (vuiRCXXy_Q      nil)
        (vuiRCXBusBit      "[]")
        (ignoreGateDiffusionFringingCap      nil)
        (vuiRCXSaveFillShapes      nil)
        (vuiQRCLayerNamePrinting      nil)
        (vuiRCXCapModels      "Do Not Include")
        (vuiStackedViaMetalWidth      "Timing")
        (vuiRCXParasiticResModels      "Include As Comment")
        (vuiRCXParasiticCapModels      "Include Model")
        (vuiRCXXy_C      nil)
        (vuiRCXParasiticResLength      nil)
    )
    ((?vuiRCXRunDetailsTab)
        (vuiRCXLSFButton      t)
        (vuiRcxMp      nil)
        (vuiRcxRunMode      "Multi Processing")
        (vuiRcxNumOfP      "")
        (machineLoc      "local")
        (vuiRCXMultiMachineButton      t)
        (vuiRcxTempDir      "/tmp")
    )

)
